# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd

  mongo-express:
    image: mongo-express:1.0.0-20
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_BASICAUTH_USERNAME: "mael"
      ME_CONFIG_BASICAUTH_PASSWORD: "maelpassword"
    depends_on:
      - mongo
